### ISSUE TITLE
libmujoco131.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Bahar-nkr** [florensacc/rllab-curriculum#18]
Hi,
When running the code maze-ant-gan, I get the problem "libmujoco131.so: cannot open shared object file: No such file or directory" while running the line self._handle = _dlopen(self._name, mode). Could you please how can I solve this problem?
Thanks a lot

**Comment by florensacc** [comment]
Have you installed MuJoCo as indicated in the documentation? https://rllab.readthedocs.io/en/latest/user/installation.html?highlight=mujoco
