### ISSUE TITLE
the definition of 'done' in step function from arm3d_disc_env

### ISSUE THREAD

**Issue by mushroom1116** [florensacc/rllab-curriculum#19]
The definition of 'done' in envs/arm3d/arm3d_disc_env.py as follow:
`done = False
if self.kill_outside and (distance_to_goal > self.kill_radius):
    print("******** OUT of region ********")
    done = True`
is that means ‘done’ is work only the disc is far from the goal？ 
And in envs/arm3d/arm3d_move_peg_env.py:
`if reward > -0.02:
    done =  True`

**Comment by florensacc** [comment]
in these environements "done" simply means that the rollout terminates. It should be called "kill", but the code we built upon used the word "done" instead.
Note that when the environment is terminated by being too far from the goal there's no reward provided!

**Comment by mushroom1116** [comment]
> in these environements "done" simply means that the rollout terminates. It should be called "kill", but the code we built upon used the word "done" instead.
> Note that when the environment is terminated by being too far from the goal there's no reward provided!

So where did you provide the reach goal reward in arm3d_disc_env?

**Comment by florensacc** [comment]
Note that arm3d_disc_env is the inner_env, and we have a wrapper that is the one that gives the actual reward.
- https://github.com/florensacc/rllab-curriculum/blob/81a3714eabfb93a6aa96c885d63b4a3602c0f72c/curriculum/experiments/starts/arm3d/arm3d_disc/arm3d_disc_brownian_algo.py#L61
- https://github.com/florensacc/rllab-curriculum/blob/master/curriculum/envs/goal_env.py#L171
Please read the code as it's executed, it will help understand it.
