### ISSUE TITLE
the definition of 'done' in step function from arm3d_disc_env

### ISSUE THREAD

**Issue by mushroom1116** [florensacc/rllab-curriculum#20]
The definition of 'done' in envs/arm3d/arm3d_disc_env.py as follow:
`done = False
if self.kill_outside and (distance_to_goal > self.kill_radius):
    print("******** OUT of region ********")
    done = True`
is that means ‘done’ is work only the disc is far from the goal？ 

And in envs/arm3d/arm3d_move_peg_env.py:
`if reward > -0.02:
    done =  True`
means 'done' is work when the disc is close to the goal enough.
I can understand the second definition but not the first. Could you please answer my question?

**Comment by florensacc** [comment]
see the other closed issue: https://github.com/florensacc/rllab-curriculum/issues/19#issuecomment-567454138
