### ISSUE TITLE
Convergence criteria for arm3d?

### ISSUE THREAD

**Issue by therealchuckliu** [florensacc/rllab-curriculum#3]
Hi, I'm running the key-hole manipulation experiments with the command in the README and it's been running for over an hour locally on my machine (2014 MBP quadcore). It seems a lot of reruns are happening - was wondering if it's possible there's some convergence criteria that's not being met or is the expected duration on the order of hours?

**Comment by florensacc** [comment]
Yes, it could take over a couple of days in a machine like yours to reach the reported performance. What do you mean exactly by "reruns"?

**Comment by therealchuckliu** [comment]
Ok, that's good to know. Just eyeballing the log output it seems the same couple tests are being run repeatedly and labeled as either itr #0 or #1

**Comment by therealchuckliu** [comment]
Oh I see, looked at the code more carefully and makes sense now. Will totally take over a day to finish running, I think I'll set up an EC2 instance instead XD. Thanks!
