### ISSUE TITLE
Could goal GAN solve the sparse reward atari game Montezuma Revenge?

### ISSUE THREAD

**Issue by nina124** [florensacc/rllab-curriculum#5]
Hi,
Wonderful work and thank you for sharing the code.
I am just curious, could goal GAN solve the sparse reward atari game Montezuma Revenge? Did you try this game?

**Comment by florensacc** [comment]
Hi,
We did not try this game, nor any Atari game for the matter. Most of them are not goal-based environments, so they do not fall directly under our framework. Nevertheless, similar curriculum generation techniques could be applied to those environments to enhance exploration.
