### ISSUE TITLE
Question about the reward

### ISSUE THREAD

**Issue by tlss94** [florensacc/rllab-curriculum#8]
Hi,

I played with the env. module
and try to set arbitrarily the start seed close to the goal

goal_coordinates=[0, 4, 0.55, 1, 0, 0, 0, 0, 1, 0, -1, 0, -1, 0, 1]
env.reset(init_state=goal_coordinates)

next_state, reward, done, d= env.step("some action")

x,y=env.wrapped_env.get_body_com("torso")[:2]

Even when I have x=0 and y=4 , I get a reward of 0...
I noticed this line in your code
https://github.com/florensacc/rllab-curriculum/blob/master/curriculum/envs/maze/maze_env.py#L250
where self.coef_inner_rew=0...

I noticed that you modifiy the "step" method compared to the rllab one:
https://github.com/rll/rllab/blob/master/rllab/envs/mujoco/maze/maze_env.py#L297-L301
How is working your step method?

Thank you,

**Comment by florensacc** [comment]
Hi,
In our implementation we totally ignore the inner rewards - and in general any reward given by the environment. The rewards we consider are only the ones given by our custom wrapper environments: https://github.com/florensacc/rllab-curriculum/blob/master/curriculum/envs/goal_env.py#L171

**Comment by tlss94** [comment]
Hi,

Thank you for your prompt answer
I guess that link refers to the Goal GAN project?
I was playing with the reverse curriculum project
but yes I see how you implement your reward.

Thank you very much

**Comment by RushToNeverLand** [comment]
> Hi,
> In our implementation we totally ignore the inner rewards - and in general any reward given by the environment. The rewards we consider are only the ones given by our custom wrapper environments: https://github.com/florensacc/rllab-curriculum/blob/master/curriculum/envs/goal_env.py#L171

So in fact, your codes use the information (distance to goal) instead of sparse reward? For example: AntMaze, the reward in AntMaze is not sparse and your codes utilize the distance information?
